version: "3"
services:
  web:
    image: vtrifonovdocker/docker-get-started:services
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
    deploy:
    command: redis-server --appendonly yes
    networks:
      - webnet
volumes:
  redis-data:
networks:
  webnet:
