kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-data-volume
  labels:
    type: local
spec:
  storageClassName: mongodb-data-volume
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/DockerDesktopVM/volumes/mongodb-data-volume" # linux directory inside DockerDesktopVM. Workarounds as mongodb requires exclusive lock which windows smb share doesn't support
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-data-claim
spec:
  storageClassName: mongodb-data-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-backups-volume
  labels:
    type: local
spec:
  storageClassName: mongodb-backups-volume
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/host_mnt/c/KubernetesVolumes/mongodb-backups-volume"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-backups-claim
spec:
  storageClassName: mongodb-backups-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-pod
  template: # create pods using pod definition in this template
    metadata:
      # unlike pod-nginx.yaml, the name is not included in the meta data as a unique name is
      # generated from the deployment name
      labels:
        app: mongodb-pod
    spec:
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-data-claim
      containers:
      - name: mongodb-prod
        image: vtrifonovdocker/mongodb:prod-v1
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        env:        
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef:
              name: mongodb
              key:  root-username.txt
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb
              key:  root-password.txt
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongodb-pod
  ports:
  - protocol: TCP
    port: 27017
