version: "3"
services:
  react:
    build:
      context: ./test-react
    image: vtrifonovdocker/test_react:v1
    ports:
      - "5000:3000"
    networks:
      - net
    volumes: 
      - "react-volume:/var/test-react"  
  nginx_host:
    image: nginx:1.14.2
    volumes: 
      - "nginx-host-volume:/usr/share/nginx/html"
    networks:
      - net
    ports:
      - "9999:80"
networks:
  net:
volumes:
  react-volume:
  nginx-host-volume:
