version: "3"
services:    
  # react:
  #   build:
  #     context: ./test-react
  #   image: vtrifonovdocker/test_react:v1
  #   ports:
  #     - "5000:3000"
  #   networks:
  #     - net
  #   volumes: 
  #     - "react-volume:/var/test-react"
  #   container_name: react-v1
  react_aspnetcore:
    build:
      context: ./AspNetCore
      dockerfile: Dockerfile
    image: vtrifonovdocker/react_aspnetcore:v3
    ports:
      - "5006:80"
    networks:
      - net
    volumes: 
      - "webserver-volume:/app"
    depends_on:
      - npm_dependencies
    command: ["bash"]
  npm_dependencies:
    build:
      context: ./AspNetCore
      dockerfile: npmDependencies.Dockerfile
      args:
        - buildenv=--env.prod
    user: "node"
    environment:
      - NODE_ENV=production  
    volumes:
      - "webserver-volume:/app"
  # npm_dependencies_prod:
  #   build:
  #     context: ./AspNetCore
  #     dockerfile: npmDependencies.Dockerfile
  #     args:
  #       buildenv: "--env.prod"
  #   user: "node"
  #   environment:
  #     - NODE_ENV=production    
  #   volumes:
  #     - "webserver-volume:/app"
  #   container_name: npm_dependencies_prod
  # nginx_host:
  #   image: nginx:1.14.2
  #   volumes: 
  #     - "nginx-host-volume:/usr/share/nginx/html"
  #   networks:
  #     - net
  #   ports:
  #     - "9999:80"
networks:
  net:
volumes:
  react-volume:
  webserver-volume: 
  nginx-host-volume:
