version: "3.2"
services:    
  react_aspnetcore_development:
    build:
      context: ./AspNetCore
      dockerfile: development.Dockerfile
    image: vtrifonovdocker/react_aspnetcore:dev-v1
    networks:
      - net-dev
    volumes: 
      - "./AspNetCore/ClientApp:/app/ClientApp"
      - "./AspNetCore/Controllers:/app/Controllers"
      - "./AspNetCore/Views:/app/Views"
      - "./AspNetCore/wwwroot:/app/wwwroot"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NODE_ENV=development      
      - CHOKIDAR_USEPOLLING=true
    container_name: react_aspnetcore_development
  nginx_host_dev:
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
      args:
        nginx_env: dev
    image: vtrifonovdocker/nginx_host:dev-v1
    ports:
      - "49999:80"
      - "49998:8081"      
      - "49997:8082"
    networks:
      - net-dev
    container_name: nginx_host_development
  mongodb_dev:
    build:
      context: ./MongoDb
    restart: always
    networks:
      net-dev:
        aliases:
          - mongo
    env_file: 
      - ./MongoDb/secrets/mongo.env #provides MONGO_INITDB_ROOT_USERNAME and MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - "mongo-dev-volume:/data/db"
    container_name: mongo-db-development
  mongodb_webapi_dev:
    build:      
      context: ./MongoDbWebApi
      dockerfile: development.Dockerfile
    networks:
      - net-dev
    env_file:
      - ./MongoDbWebApi/secrets/webApiSecrets.dev.env #provides MONGO_DB_WEB_API_CONNECTION_STRING
    volumes:
      - "./MongoDbWebApi/WebApi:/app/WebApi"
    container_name: mongodb_webapi_development
  sql_server_webapi_dev:
    build:      
      context: ./SqlServerWebApi
      dockerfile: development.Dockerfile
    networks:
      - net-dev
    volumes:
      - "./SqlServerWebApi/WebApi:/app/WebApi"
    container_name: sql_server_webapi_development
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./SqlServerWebApi/secrets/sqlServerWebApiSecrets.dev.env
  sql_server_development:
    build:
      context: ./SqlServer
      dockerfile: Dockerfile
    image: vtrifonovdocker/sql_server:dev-v1
    ports:
      - "1433:1433"
    networks:
      - net-dev
    env_file:
      - ./SqlServer/secrets/sqlServerSecrets.dev.env
    volumes:
      - "./SqlServer/createDb:/usr/createDb"
    container_name: sql_server_development
networks:
  net-dev:
volumes:
  webserver-dev-volume:
  mongo-dev-volume:  
